language: python
python:
  - "3.0"
  - "3.1"
  - "3.2"
  - "3.3"
  - "3.4"
# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install: pip install -r requirements.txt
# command to run tests, e.g. python setup.py test
script: nose2 --with-cov --cov-report html --cov-report term
