#USER_TIME_FORMAT = '%Y-%m-%d %H:%M:%S'
#SERIES_TIME_FORMAT = '%Y-%m-%d'
#NULL_TIME = '0000-00-00'

USER_AGENT = 'api-indiv-0829BA2B33942A4A5E6338FE05EFB8A1'
XMLS_DIRECTORY = 'XML_TEMPLATES'
EXAMPLES_DIRECTORY = "EXAMPLES"

HOST_NAME = "http://myanimelist.net"

DEBUG = True
RETRY_NUMBER = 4